# 应用名称
spring.application.name: dc_system
# 数据库驱动：
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # 数据源名称
    name: defaultDataSource
    # 数据库连接地址
    url: jdbc:mysql://localhost:3306/dc_system?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    # 数据库用户名&密码：
    username: root
    password: w8080808
# 应用服务 WEB 访问端口
server.port: 8080
#下面这些内容是为了让MyBatis映射
#指定Mybatis的Mapper文件
mybatis:
  mapper-locations: classpath*:mappers/*xml
  #指定Mybatis的实体目录
  type-aliases-package: com.java.dc_system.pojo
  #指定Mybatis日志输出类型
  configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

